### ISSUE TITLE
When selecting any printer under administrator, "enter name of computer" screen comes up twice

### ISSUE THREAD

**Issue by richard-frink** [JalIrani/tomsoft#28]

**Comment by nlicci1** [comment]
What OS are you running?

**Comment by richard-frink** [comment]
This was done while running the most updated version of the UI branch, this does not happen with the dev branch, sorry for not clarifying that.

**Comment by nlicci1** [comment]
@rsussan you are supposed to be testing code on the "develop" branch. That branch has the most stable code that is not ready for a release (meaning it is ready to be tested). Since you have already posted issues that seem to be on different branches please reference those branches in your ticket/issue. 

Please from now on checkout out the "develop" branch and test off of the most recent commit.
