### ISSUE TITLE
Student profile functionality

### ISSUE THREAD

**Issue by miguelTowsonCompSci** [JalIrani/tomsoft#6]
checks table to see if the TU ID is in the student table if so prompt to verify name. If not allow them to enter data. (non UI side)

**Comment by danthony1** [comment]
A class has been made to house this action. It still needs to connect to the other classes and database. The UI also needs to be changed.

**Comment by nlicci1** [comment]
For this you would need to be able to: create a new student profile (check new TUID against existing ones) and then enter TUID and submit a file.

Remember when you create a new student that is where they would enter in their info (name, tuid, email). This means that the current student submission page is out of date becuase it has you enter that info in every time you want to submit file.

This means you will have to create a method for this process that utilizes the database (use methods in SQLMethods.java) to get that information to display in the student submission page (instead of entering it in every time).
